# INTRO AND GETTING STARTED WITH NUMPY

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
mylist = [1,2,3,4,5,6]
print(type(mylist))
print(mylist)

<class 'list'>
[1, 2, 3, 4, 5, 6]


import numpy as np
arr2 = np.array([5,6,7,8,9])
print(arr2)

In [5]:
print(np.__version__) # here __version__ is an attribute of the numpy module

2.3.0


# NumPy creating arrays

#### To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [6]:
#creating array using tuple
tarr= np.array((1,2,3,4,5))
print(tarr)
print(type(tarr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#creating array using Lsit
larr = np.array([1,2,3,4,5])
print(larr)
print(type(larr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dictionary is not a array-like object

## Nested Arrays

#### 0-d array / scalar

In [8]:
a1 = np.array(69)
print(a1)
print(type(a1))

69
<class 'numpy.ndarray'>


#### 1-d array / vector

In [9]:
a2 = np.array([70,71,72,73,74])
print(a2)

[70 71 72 73 74]


#### 2d array : array that has 1d array as its elements

In [10]:
a2 = np.array([[70,71,72,73,74],[2,4,6,8,20]])
print(a2)

[[70 71 72 73 74]
 [ 2  4  6  8 20]]


In [11]:
print(type(a2))

<class 'numpy.ndarray'>


#### 3-D arrays : An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [12]:
a3 = np.array([[[2,3,5,7],[1,2,3,4]],
               [[1,3,5,7],[2,4,6,8]]])
print(a3)

[[[2 3 5 7]
  [1 2 3 4]]

 [[1 3 5 7]
  [2 4 6 8]]]


### NOTE : NumPy has a whole sub module dedicated towards matrix operations called numpy.mat



In [13]:
a = np.array(69)
b = np.array([70,71,72,73,74])
c = np.array([[70,71,72,73,74],[2,4,6,8,20]])
d = np.array([[[2,3,5,7],[1,2,3,4]],
               [[1,3,5,7],[2,4,6,8]]])


In [14]:
#NumPy Arrays provides the ndim aprttribute that returns an integer that tells us how many dimensions the array have
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [15]:
arr = np.array([1,2,3] , ndmin = 5) # When the array is created, you can define the number of dimensions by using the ndmin argument.
print(arr)

[[[[[1 2 3]]]]]


In [16]:
print(arr.ndim) 

5


In [17]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
zeros.dtype

dtype('float64')

In [19]:
type(zeros)

numpy.ndarray

In [20]:
rng=np.arange(15)

In [21]:
print(rng)
print(type(rng))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [22]:
lspace = np.linspace(1,100,20)
print(lspace)
print(type(lspace))

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]
<class 'numpy.ndarray'>


In [23]:
print(lspace.size)

20


In [24]:
emp = np.empty((4,6))
print(emp) 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
emp.ndim

2

In [26]:
emp.shape

(4, 6)

In [27]:
emp.size

24

In [28]:
ide = np.identity(45) #gives a identitiy matrix of order 45 * 45

In [29]:
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [30]:
ide.size 

2025

In [31]:
ide.shape

(45, 45)

# ARRAY INDEXING & accessing

In [32]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [33]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4
5


In [34]:
print(arr[0]+arr[3])

5


In [35]:
#accessing elements of a 2d array 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd ele of the 1st row :" ,arr[0,1])
print(arr[0])

2nd ele of the 1st row : 2
[1 2 3 4 5]


In [36]:
#accessing elements of a 3d array 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
print("1st layer from top-1st row-1st col ele is : ",arr[0,0,0])

1st layer from top-1st row-1st col ele is :  1


In [38]:
print(arr[0, 1, 2])


6


In [39]:
#To print 12 : 2nd layer ,2nd row, 3rd col
print(arr[1,1,2])

12


In [40]:
#-ve indexing
print(arr[-1,-1,-1])
##1st layer from bottom , last row, last col

12


# slicing

In [41]:
#slicing 1d array 
arr = np.array([1,2,3,4,5,6,7])
print(arr[3::])
print(arr[-1::-1])

[4 5 6 7]
[7 6 5 4 3 2 1]


#### slicing 2d array
#### From the second element, slice elements from index 1 to index 4 (not included):

In [42]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr[1,1:4]) #Note: Remember that second element has index 1

[7 8 9]


#### From both elements, return index 2:

In [43]:
print(arr[0:2,2]) #slicing 

[3 8]


In [44]:
print(arr[0,2] , arr[1,2]) #indexing

3 8


#### From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [45]:
print(arr[0:,1:4])

[[2 3 4]
 [7 8 9]]


# Data Types

In [46]:
#The NumPy array object has a property called dtype that returns the data type of the array:

import numpy as np
arr = np.array([1.2,2.4,6,24])
print(type(arr))
print(arr.dtype) #prints data type of elements in array 

<class 'numpy.ndarray'>
float64


In [47]:
p = np.array([True , False, 0, 1])
b = np.array([True , False])
s = np.array(["alpha",'beeta','delta','pro','sridhar'])
print(type(p))
print(p.dtype)

print(type(b))
print(b.dtype)

print(type(s))
print(s.dtype)#  U - unicode string (4 bytes per character , multi-lang & emoji support)

<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
bool
<class 'numpy.ndarray'>
<U7


#### Creating Arrays With a Defined Data Type

In [48]:
arr = np.array([1,2,3,4,5] , dtype = 'S') # S - byte string (1 bytes per character , doesnt support multi-lang & emoji )

In [49]:
print(arr)

[b'1' b'2' b'3' b'4' b'5']


In [50]:
arr = np.array([1,2,3,4,5] , dtype = 'f') # f - float 

In [51]:
print(arr)

[1. 2. 3. 4. 5.]


In [52]:
arr = np.array(['a', '2', '3'], dtype='i') # A non integer string like 'a' can not be converted to integer 


ValueError: invalid literal for int() with base 10: 'a'

#### Converting Data Type on Existing Arrays

In [53]:
# astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# The data type can be specified using a string, like 'f' for float, 'i' for integer etc.
# or you can use the data type directly like float for float and int for integer.

arr = np.array([1,2,3,5,6])
newarr = arr.astype(float)
otherarr = arr.astype(str)

print(newarr)
print(newarr.dtype)

print(otherarr)
print(otherarr.dtype)

[1. 2. 3. 5. 6.]
float64
['1' '2' '3' '5' '6']
<U21


In [54]:
print(arr)
print(arr.dtype)

[1 2 3 5 6]
int64


In [55]:
arr = np.array([0,0.1,1,2])
boolarr = arr.astype(bool)
print(boolarr)
print(boolarr.dtype)

[False  True  True  True]
bool


# NumPy Array Copy vs View

In [56]:
#### The copy owns the data and any changes made to the copy will not affect original array, and vice versa
#### The view does not own the data and any changes made to the view will affect the original array, and vice versa

####  Make a copy, change the original array, and display both arrays:

In [57]:
arr = np.array([11,22,33,44,55])
x = arr.copy() #copies the arr into new arr
x[3] = 69

print(arr)
print(x)

[11 22 33 44 55]
[11 22 33 69 55]


#### Make a view, change the original array, and display both arrays:

In [58]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42  #The view SHOULD be affected by the changes made to the original array.

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [59]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31  #The original array SHOULD be affected by the changes made to the view.

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


#### Check if Array Owns its Data

In [60]:
#### Every NumPy array has the attribute base that returns None if the array owns the data.
#### Otherwise, the base  attribute refers to the original object.

In [61]:
arr = np.array([1, 2, 3, 4, 5])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape

#### shape : The shape of an array is the number of elements in each dimension

In [62]:
a = np.array([1,2,3])
b = np.array([[1,2,3],
              [4,5,6]])
c = np.array([[[1,2,3],
              [4,5,6]],
             
             [[11,22,33],
              [44,55,66]]])

In [63]:
print(a.shape , b.shape , c.shape) #returns a tuple with each index having the number of corresponding elements.

(3,) (2, 3) (2, 2, 3)


In [64]:
# Create an array with 5 dimensions using ndmin using a vector with values 11,22,33,44 and verify that last dimension has value 4:

arr = np.array([11,22,33,44] , ndmin = 5)
print(arr.shape)

(1, 1, 1, 1, 4)


# NumPy Array Reshape

In [65]:
#### Convert the following 1-D array with 12 elements into a 2-D array.
#### The outermost dimension will have 4 arrays, each with 3 elements:

# completed till numpy array reshape

### BUT THEN MISTAKELY IVE BACKSPACED THE COMPLETE THING , UNAWARE OF THE FACT THIS BLODDY APP DOESNT HAVE A FEATURE TO UNDO THE ACTION HATS OFF TO THE DEVELPOERS !!!!!

In [66]:
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
a=arr.reshape(-1)
print(a)
print(arr.reshape(12))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


---

In [67]:
import numpy as np
linspace=np.linspace(10,690,75)
print(linspace) # creates equally spaced 75 elements from 10 to 690

[ 10.          19.18918919  28.37837838  37.56756757  46.75675676
  55.94594595  65.13513514  74.32432432  83.51351351  92.7027027
 101.89189189 111.08108108 120.27027027 129.45945946 138.64864865
 147.83783784 157.02702703 166.21621622 175.40540541 184.59459459
 193.78378378 202.97297297 212.16216216 221.35135135 230.54054054
 239.72972973 248.91891892 258.10810811 267.2972973  276.48648649
 285.67567568 294.86486486 304.05405405 313.24324324 322.43243243
 331.62162162 340.81081081 350.         359.18918919 368.37837838
 377.56756757 386.75675676 395.94594595 405.13513514 414.32432432
 423.51351351 432.7027027  441.89189189 451.08108108 460.27027027
 469.45945946 478.64864865 487.83783784 497.02702703 506.21621622
 515.40540541 524.59459459 533.78378378 542.97297297 552.16216216
 561.35135135 570.54054054 579.72972973 588.91891892 598.10810811
 607.2972973  616.48648649 625.67567568 634.86486486 644.05405405
 653.24324324 662.43243243 671.62162162 680.81081081 690.        ]


In [68]:
(386.75675676-395.94594595)

-9.189189190000036

In [69]:
(28.37837838-37.56756757) 

-9.18918919

In [70]:
linspace.size

75

In [71]:
linspace.dtype

dtype('float64')

In [72]:
a = np.array([1,2,3])
b = np.array([3,4,5])

In [73]:
a+b

array([4, 6, 8])

In [74]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

---


In [75]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [65]:
br = np.array(x)

In [77]:
br

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
br.sum(axis = 0)

array([12,  8,  9])

In [79]:
br.sum(axis = 1)

array([ 6, 15,  8])

In [80]:
br.T # Transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [81]:
for item in br.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [82]:
br.size

9

In [83]:
br.shape

(3, 3)

In [66]:
br.nbytes # gives total bytes consumed

8

In [87]:
one = np.array([1,2,34,5,6,67,23])

In [90]:
one.argmax() # returns the index of maxm val

np.int64(5)

In [91]:
one.argmin() # returns the index of minm val

np.int64(0)

In [92]:
one.argsort() # gives an array  of indexes , of ascending order of sorted array 


array([0, 1, 3, 4, 6, 2, 5])

---

# lambda FUnction

In [5]:
# syntax:
# lambda arguments : expression

Q.Add 10 to argument a, and return the result:

In [6]:
x = lambda a: a+10

In [7]:
print(x(69))

79


Q.Multiply argument a with argument b and return the result:

In [10]:
y = lambda a,b: a*b
print(y(6,9))


54


Q.Summarize argument a, b, and c and return the result:

In [11]:
s = lambda a,b,c : a+b+c
print(s(69,6,9))

84


---

# map() function

SYNTAX : map(function, iterables)

In [48]:
def myfun(n):
    return len(n)
x = map(myfun , ['apple','banana','potato'])

In [49]:
print(x)

In [50]:
print(list(x))

[5, 6, 6]


Q.Make new fruits by sending two iterable objects into the function:

In [57]:
def myfun(a,b):
    return a+b
new = map(myfun , ['apple' , 'banana' , 'grapes'],['orange' , 'pumpkin' , 'papaya'])

In [59]:
print(list(new))

['appleorange', 'bananapumpkin', 'grapespapaya']


# Filter() Function

SYNTAX : filter(function, iterable)

In [61]:
# Filter the array, and return a new array with only the values equal to or above 18:
ages = [5, 12, 17, 18, 24, 32]
adult  = list(filter(lambda a : a>=18,ages))
print(adult)

[18, 24, 32]


---

# all() Function

SYNTAX : all(iterable) 

In [62]:
# iterable - (list, tuple, dictionary)

Q.Check if all items in a list are True

In [67]:
a = all([0,1,1,0])
b = all([1,1,1])

In [68]:
print (a,b)

False True


Q.Check if all items in a tuple are True:

In [73]:
x = all((0,True,False))
xx = all((True,True))
print(x , xx)

False True


Q.Check if all items in a dictionary are True:


In [75]:
mydict = {0 : "Apple", 1 : "Orange"} 
x = all(mydict) # When used on a dictionary, the all() function checks if all the keys are true, not the values.
print(x)

False


# LIST COMPREHENSION

List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.

In [78]:
fruits = ['apple' ,'banana' ,'grapes', 'kiwi']
newlist = []

for i in fruits:
    if "a" in i:
        newlist.append(i)
print(newlist)

['apple', 'banana', 'grapes']


SYNTAX : newlist = [expression **for** item **in** iterable **if** condition == True]

Q.Only accept items that are not "apple":

In [81]:
newlist = [x for x in fruits if x != "apple"] #The condition is like a filter that only accepts the items that evaluate to True
print(newlist)

['banana', 'grapes', 'kiwi']


Q.Accept only numbers lower than 5:

In [91]:
newlist = [ i for i in range(0,30) if i < 5]
print(newlist)

[0, 1, 2, 3, 4]


In [85]:
# The expression can also contain conditions, not like a filter, but as a way to manipulate the outcome


Q.Return "orange" instead of "banana":

In [87]:
newlist = [i if i!='banana' else "orange" for i in fruits] # Return the item if it is not banana, if it is banana return orange".
print(newlist)

['apple', 'orange', 'grapes', 'kiwi']


In [88]:
newlist = ['apple' for i in fruits]

In [89]:
print(newlist)

['apple', 'apple', 'apple', 'apple']


# ARRAY MODIFICATION


#### insert( array , index, value, axis = none)
axis = 0 : row -wise ;
axis = 1 : col -wise

In [3]:
import numpy as np

arr = np.array(range(0,6))
print(arr)
new_arr = np.insert(arr, 2, 100, axis =0)
print(new_arr)

[0 1 2 3 4 5]
[  0   1 100   2   3   4   5]


In [6]:
new_arr = np.insert(arr, 2, 69) 
print(new_arr)

[ 0  1 69  2  3  4  5]


#### inset insert in 2d

In [8]:
arr_2d = np.array([[1,2],[3,4]])
new_arr_2d = np.insert(arr_2d,1,[5,6],axis = 0)
print(new_arr_2d)

[[1 2]
 [5 6]
 [3 4]]


In [12]:
other_2d = np .insert(new_arr_2d,1,[69,69,69],axis = 1)
print(other_2d)

[[ 1 69  2]
 [ 5 69  6]
 [ 3 69  4]]


In [16]:
flat = np.insert(new_arr_2d , 1 ,[11,22,33,44] ,axis = None)
print(flat)

[ 1 11 22 33 44  2  5  6  3  4]


#### append = add ele at end

In [19]:
arr = np.append(flat,[132,456])

In [20]:
print(arr)

[  1  11  22  33  44   2   5   6   3   4 132 456]


In [25]:
new = new_arr_2d.flatten()
print(new)

[1 2 5 6 3 4]


# concatinate 2 arrays STACKING

axis = 0 > VERTICAL STACKING  
axis = 1 > HORIZONTAL STACKING 

In [32]:
arr1 = np.array([1,2,4])
arr2 = np.array([3,5,6])
myarr = arr1+arr2
conc = np.concatenate((arr1,arr2))
print(myarr)
print(conc)

[ 4  7 10]
[1 2 4 3 5 6]


In [36]:
arr3= np.array([11,22,33,44])
conc2 = np.concatenate((arr1,arr3))
print(conc2)

[ 1  2  4 11 22 33 44]


#### delete()

syntax = np.delete(Array , indexm axis=none)

In [37]:
arr = np.array(range(10,60,10))

In [38]:
print(arr)
new = np.delete (arr,0)
print(new)

[10 20 30 40 50]
[20 30 40 50]


In [52]:
arr2d = np.array([[1,2],[3,4],[11,22]])
x = np.delete(arr2d,2,axis =0)
y= np.delete(arr2d,0,axis =1)
print(x)
print(y)

[[1 2]
 [3 4]]
[[ 2]
 [ 4]
 [22]]


#### vertical and horizontal stacking

vstack() row wise ;
hstack() col wise

In [69]:
arr1 = np.array([11,22,33,44,55,66])
arr2 = np.array([1,2,3,4,5,66])


print("vert stacking :\n",np.vstack((arr1,arr2)))
print("hor stacking :",np.hstack((arr1,arr2)))


vert stacking :
 [[11 22 33 44 55 66]
 [ 1  2  3  4  5 66]]
hor stacking : [11 22 33 44 55 66  1  2  3  4  5 66]


#### vertical and horizontal splitting
vsplit() row wise ; hsplit() col wise

In [70]:
print(np.split(arr1,2))

[array([11, 22, 33]), array([44, 55, 66])]


# zip() function